### ISSUE TITLE
Buttons on homepage doesn't use translations

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/wiki#24]
Buttons on the homepage are untranslatable or they don't use translation

**Comment by ss-o** [comment]
Not use what was the issue exactly but after assigning unique id buttons translation worked. Possibly had a conflict or some confusion in context to assign it.

https://github.com/z-shell/wiki/blob/4db4b529d07e59b5f43e99331de0207a99fc459c/src/pages/index.tsx#L47

https://github.com/z-shell/wiki/blob/4db4b529d07e59b5f43e99331de0207a99fc459c/src/pages/index.tsx#L58

**Comment by 0xMRTT** [comment]
Thanks
