### ISSUE TITLE
docs: Possible issue with LS_COLORS documentation

### ISSUE THREAD

**Issue by callistachang** [z-shell/wiki#253]
### Which locale the issue is related?

{"label"=>"English"}

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/zi/blob/main/docs/CONTRIBUTING.md).

### Description

I used the following snippet found in https://wiki.zshell.dev/docs/guides/syntax/standard#ls_colors to set up LS_COLORS in my .zshrc file:

```sh
zi ice atclone'dircolors -b LS_COLORS > clrs.zsh' \
  atpull'%atclone' pick"clrs.zsh" nocompile'!' \
  atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zi light trapd00r/LS_COLORS
```

However, it clashed with usage of https://github.com/Aloxaf/fzf-tab, giving the error "bad set of key/value pairs for associative array". I found the answer on this issue: https://github.com/Aloxaf/fzf-tab/issues/100; I removed the `“` surrounding `{(s.:.)LS_COLORS}` to remove the error:

```sh
zi ice atclone'dircolors -b LS_COLORS > clrs.zsh' \
  atpull'%atclone' pick"clrs.zsh" nocompile'!' \
  atload'zstyle ":completion:*" list-colors ${(s.:.)LS_COLORS}'
zi light trapd00r/LS_COLORS
```

Can I propose to update the docs to remove the `“` surrounding `{(s.:.)LS_COLORS}` to increase compatibility with other plugins?

Thanks!

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by ss-o** [comment]
Hi @callistachang, your proposal is reasonable and always welcomed, thank you for pointing this out :dart: :handshake:
