### ISSUE TITLE
[docs]: +zi-message usage

### ISSUE THREAD

**Issue by ss-o** [z-shell/wiki#33]

**Comment by 0xMRTT** [comment]
Where this should be added ? In zi source code ? On the wiki ?

**Comment by ss-o** [comment]
I think in syntax as:

https://wiki.zshell.dev/docs/guides/syntax/zi_messages

or add header at:

https://wiki.zshell.dev/docs/guides/commands#zi-messages

**Comment by ss-o** [comment]
use `zi-pallete` from dotfiles and I add more info about messages.

**Comment by 0xMRTT** [comment]
#59
