### ISSUE TITLE
docs: add zoxide to the gallerie of invocation > programs

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/wiki#69]
### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/zi/blob/main/docs/CONTRIBUTING.md).

### Description

https://github.com/ajeetdsouza/zoxide

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by ss-o** [comment]
```
git fetch origin
git checkout 69-docs-add-zoxide-to-the-gallerie-of-invocation-programs
```

**Comment by 0xMRTT** [comment]
Already created a branch called `issue-68`
