### ISSUE TITLE
docs: add zoxide to the gallerie of invocation > plugins

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/wiki#70]
### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/zi/blob/main/docs/CONTRIBUTING.md).

### Description

https://github.com/z-shell/zsh-zoxide

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by ss-o** [comment]
```
git fetch origin
git checkout 70-docs-add-zoxide-to-the-gallerie-of-invocation-plugins
```

**Comment by 0xMRTT** [comment]
Already created a branch called issue-70

**Comment by ss-o** [comment]
So why open the issue?

**Comment by 0xMRTT** [comment]
For saying that i'm working on and add in Projects
