### ISSUE TITLE
docs: add more informations in CONTRIBUTING

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/wiki#74]
### Description

When you go to CONTRIBUTING, you only get basic about the project license and membership. I think that it would be great to add a section which explain how to contribute or add links of useful information like STYLEGUIDE, GUIDELINES, etc

### Self-service

- [x] I'd be willing to address this documentation request myself.

```
git fetch origin
git checkout 74-docs-add-more-informations-in-contributing
```

**Comment by ss-o** [comment]
Do as separate files and provide links in CONTRIBUTING.md.

**Comment by 0xMRTT** [comment]
https://wiki.zshell.dev/legal/CONTRIBUTING?static=true
