### ISSUE TITLE
docs: replace antigen with antidote

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/wiki#77]
### Description

Antigen seems to be dead (no merge from [2019](https://github.com/zsh-users/antigen/issues/725) ). There is two successor:
- antibody which is also dead
- antidote https://github.com/mattmc3/antidote

So, it would be great to replace antigen with antidote.

https://github.com/mattmc3/antidote/issues/31

### Self-service

- [X] I'd be willing to address this documentation request myself.

```
git fetch origin
git checkout 77-docs-replace-antigen-with-antidote
```

**Comment by ss-o** [comment]
#67 will clean antigen.
