### ISSUE TITLE
docs: ecosystem > annexes > test : Add Zunit as required dependency

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/wiki#78]
### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/zi/blob/main/docs/CONTRIBUTING.md).

### Description

You need to have zunit installed but not specified in the doc

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by 0xMRTT** [comment]
```
git fetch origin
git checkout 78-docs-ecosystem-annexes-test-add-zunit-as-required-dependency
```

**Comment by 0xMRTT** [comment]
```
 zi for z-shell/z-a-meta-plugins @zunit
```

**Comment by ss-o** [comment]
The file seems to be outdated.
